import { ask } from "../lib/ai.js";
import { getUsername, listUserRepos, getRepoLanguages, getFileContent } from "../lib/github.js";
import { exec, execSafe } from "../lib/fs.js";
import path from "path";
import fs from "fs-extra";

interface AutoFeatureOptions {
  repo?: string;
  dryRun: boolean;
  workDir: string;
}

const PORTFOLIO_REPOS = [
  "ai-chat-platform",
  "gh-auto",
  "realtime-dash",
  "taskflow",
  "api-hub",
  "web-summarizer",
];

interface FeatureIdea {
  repo: string;
  feature: string;
  files: string[];
}

async function pickRepoAndFeature(repos: string[]): Promise<FeatureIdea> {
  const username = getUsername();

  // Pick a random repo or use the specified one
  const repo = repos[Math.floor(Math.random() * repos.length)];

  // Get context about the repo
  const pkg = await getFileContent(username, repo, "package.json");
  const readme = await getFileContent(username, repo, "README.md");
  const languages = await getRepoLanguages(username, repo);

  const response = await ask(
    `Suggest ONE small, useful feature to add to this project.

Repo: ${repo}
Languages: ${JSON.stringify(languages)}
Package.json: ${pkg?.substring(0, 500) ?? "N/A"}
README excerpt: ${readme?.substring(0, 800) ?? "N/A"}

Requirements:
- Must be a SMALL feature (1-3 files changed, under 200 lines total)
- Should be a genuine improvement (not busywork)
- Good examples: add loading states, improve error handling, add a new API endpoint, add keyboard shortcuts, add search/filter, improve mobile responsiveness, add unit tests for a function
- Bad examples: rewrite the whole app, add authentication, change the database

Return JSON with:
- repo: "${repo}"
- feature: one-sentence description of the feature
- files: array of file paths that would be modified

Return ONLY the JSON, no explanation.`,
    {
      system: "You are a senior developer suggesting small, valuable improvements to existing projects. Return valid JSON only.",
      maxTokens: 512,
    }
  );

  try {
    const jsonStr = response.replace(/```json?\n?/g, "").replace(/```/g, "").trim();
    return JSON.parse(jsonStr);
  } catch {
    return {
      repo,
      feature: "add loading states and error boundaries to UI components",
      files: ["src/components/"],
    };
  }
}

export async function autoFeature(options: AutoFeatureOptions): Promise<void> {
  const username = getUsername();
  const targetRepos = options.repo ? [options.repo] : PORTFOLIO_REPOS;

  console.log(`\n🔧 Auto-feature generator\n`);

  // Pick a feature
  console.log("   ⏳ Selecting repo and generating feature idea...");
  const idea = await pickRepoAndFeature(targetRepos);

  console.log(`   📦 Repo: ${idea.repo}`);
  console.log(`   ✨ Feature: ${idea.feature}`);
  console.log(`   📝 Files: ${idea.files.join(", ")}\n`);

  if (options.dryRun) {
    console.log("   (dry run — would clone, implement, and push)\n");
    return;
  }

  // Clone the repo
  const cloneDir = path.join(options.workDir, idea.repo);
  if (await fs.pathExists(cloneDir)) {
    console.log("   ⏳ Pulling latest...");
    exec("git pull", cloneDir);
  } else {
    console.log("   ⏳ Cloning repo...");
    exec(
      `gh repo clone ${username}/${idea.repo} ${cloneDir}`,
      options.workDir
    );
  }

  // Install deps
  console.log("   ⏳ Installing dependencies...");
  execSafe("npm install", cloneDir);

  // Use the build-feature command logic
  // We import dynamically to avoid circular deps
  const { buildFeature } = await import("./build-feature.js");
  await buildFeature({
    projectDir: cloneDir,
    feature: idea.feature,
    dryRun: false,
  });

  // Push the feature branch
  console.log("   ⏳ Pushing to GitHub...");
  const branch = execSafe("git branch --show-current", cloneDir);
  if (branch && branch !== "main") {
    execSafe(`git push -u origin ${branch}`, cloneDir);
    console.log(`   ✓ Pushed branch: ${branch}`);

    // Create a PR
    const prResult = execSafe(
      `gh pr create --repo ${username}/${idea.repo} --title "feat: ${idea.feature}" --body "Auto-generated feature improvement.\n\n${idea.feature}\n\nGenerated by portfolio-agents auto-feature." --head ${branch}`,
      cloneDir
    );
    if (prResult) {
      console.log(`   ✓ PR created: ${prResult}`);
    }
  } else {
    execSafe("git push", cloneDir);
    console.log("   ✓ Pushed to main");
  }

  console.log(`\n✅ Feature added to ${idea.repo}!\n`);
}
