import path from "path";
import fs from "fs-extra";
import { ask } from "../lib/ai.js";
import {
  getUsername,
  listUserRepos,
  getRepoLanguages,
  getRepoTopics,
  getLatestCommits,
} from "../lib/github.js";
import { writeProjectFile, exec, execSafe } from "../lib/fs.js";

interface SyncOptions {
  portfolioDir: string;
  dryRun: boolean;
}

interface ProjectData {
  name: string;
  description: string | null;
  url: string;
  homepage: string | null;
  languages: Record<string, number>;
  topics: string[];
  stars: number;
  updatedAt: string;
  recentCommits: string[];
}

const SHOWCASE_REPOS = [
  "ai-chat-platform",
  "gh-auto",
  "realtime-dash",
  "taskflow",
  "api-hub",
  "web-summarizer",
  "portfolio-agents",
];

async function fetchProjectData(): Promise<ProjectData[]> {
  const username = getUsername();
  const repos = await listUserRepos(username);
  const projects: ProjectData[] = [];

  const showcaseRepos = repos.filter((r) => SHOWCASE_REPOS.includes(r.name));

  for (const repo of showcaseRepos) {
    console.log(`   📦 Fetching data for ${repo.name}...`);

    const [languages, topics, commits] = await Promise.all([
      getRepoLanguages(username, repo.name),
      getRepoTopics(username, repo.name),
      getLatestCommits(username, repo.name, 5).catch(() => []),
    ]);

    projects.push({
      name: repo.name,
      description: repo.description,
      url: repo.html_url,
      homepage: repo.homepage ?? null,
      languages,
      topics,
      stars: repo.stargazers_count ?? 0,
      updatedAt: repo.updated_at ?? "",
      recentCommits: commits.map((c) => c.commit.message.split("\n")[0]),
    });
  }

  return projects;
}

function generateProjectCard(project: ProjectData): string {
  const langs = Object.keys(project.languages).slice(0, 4);
  const techPills = langs.map((l) => `<span class="tech-pill">${l}</span>`).join("\n          ");

  return `    {
      name: "${project.name}",
      title: "${formatTitle(project.name)}",
      description: ${JSON.stringify(project.description ?? "")},
      url: "${project.url}",
      homepage: ${project.homepage ? `"${project.homepage}"` : "null"},
      languages: ${JSON.stringify(langs)},
      topics: ${JSON.stringify(project.topics)},
      stars: ${project.stars},
      updatedAt: "${project.updatedAt}",
    }`;
}

function formatTitle(name: string): string {
  return name
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

async function generateProjectPage(project: ProjectData): Promise<string> {
  return ask(
    `Generate an Astro page for a portfolio project. This goes in src/pages/projects/${project.name}.astro.

Project data:
${JSON.stringify(project, null, 2)}

The page should:
- Import Layout from "../../layouts/Layout.astro"
- Show project title, description, tech stack pills, and links (GitHub + live demo if homepage exists)
- List recent commits
- Have a "Back to Projects" link
- Use CSS variables: var(--bg-surface), var(--text-primary), var(--text-secondary), var(--accent)
- Be responsive

Return ONLY the .astro file content, no explanation.`,
    {
      system: "You are a frontend developer generating Astro components. Return only the file content.",
      maxTokens: 4096,
    }
  );
}

async function generateDataFile(projects: ProjectData[]): Promise<string> {
  const cards = projects.map(generateProjectCard).join(",\n");
  return `// Auto-generated by portfolio-agents sync command
// Last synced: ${new Date().toISOString()}

export interface Project {
  name: string;
  title: string;
  description: string;
  url: string;
  homepage: string | null;
  languages: string[];
  topics: string[];
  stars: number;
  updatedAt: string;
}

export const projects: Project[] = [
${cards}
];
`;
}

export async function syncPortfolio(options: SyncOptions): Promise<void> {
  const portfolioDir = path.resolve(options.portfolioDir);

  if (!(await fs.pathExists(portfolioDir))) {
    throw new Error(`Portfolio directory not found: ${portfolioDir}`);
  }

  console.log(`\n🔄 Syncing portfolio site: ${portfolioDir}\n`);

  // Fetch all project data from GitHub
  console.log("   ⏳ Fetching project data from GitHub...\n");
  const projects = await fetchProjectData();

  if (projects.length === 0) {
    console.log("   ⚠ No showcase repos found on GitHub. Push projects first.");
    return;
  }

  console.log(`\n   Found ${projects.length} projects.\n`);

  // Generate data file
  console.log("   ⏳ Generating project data file...");
  const dataContent = await generateDataFile(projects);

  if (options.dryRun) {
    console.log("\n--- src/data/projects.ts ---\n");
    console.log(dataContent);
  } else {
    await writeProjectFile(portfolioDir, "src/data/projects.ts", dataContent);
    console.log("   ✓ src/data/projects.ts updated");
  }

  // Generate individual project pages
  for (const project of projects) {
    console.log(`   ⏳ Generating page for ${project.name}...`);
    const page = await generateProjectPage(project);

    if (options.dryRun) {
      console.log(`\n--- src/pages/projects/${project.name}.astro (preview) ---\n`);
      console.log(page.substring(0, 500) + "...\n");
    } else {
      await writeProjectFile(portfolioDir, `src/pages/projects/${project.name}.astro`, page);
      console.log(`   ✓ src/pages/projects/${project.name}.astro`);
    }
  }

  if (!options.dryRun) {
    // Try to build
    console.log("\n   ⏳ Rebuilding portfolio site...");
    const buildResult = execSafe("npm run build 2>&1", portfolioDir);

    if (buildResult !== null) {
      console.log("   ✓ Build succeeded");

      // Commit and push
      try {
        exec("git add -A", portfolioDir);
        exec(
          `git commit -m "sync: update project data from GitHub" --author="George Castillo <gcasti256@users.noreply.github.com>"`,
          portfolioDir
        );
        console.log("   ✓ Changes committed");

        const hasRemote = execSafe("git remote get-url origin", portfolioDir);
        if (hasRemote) {
          exec("git push", portfolioDir);
          console.log("   ✓ Pushed to GitHub (Pages will auto-deploy)");
        }
      } catch {
        console.log("   ℹ No changes to commit");
      }
    } else {
      console.log("   ⚠ Build failed — files written but not pushed. Fix and retry.");
    }
  }

  console.log(`\n✅ Portfolio sync ${options.dryRun ? "previewed" : "complete"}!\n`);
}
